# Use postgres/example user/password credentials
version: '3.9'
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
     - POSTGRES_USER=<db_user>
     - POSTGRES_PASSWORD=<db_password>
     - POSTGRES_DB=POSTGRES_USER
    volumes:
     - postgres-data:/var/lib/postgresql/data
    user: ${UID}:${GID}
    ports:
     - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  postgres-data: 